// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

//template:end imports

//template:begin types
type NetworkAccessAuthenticationRulesBulk struct {
	Id          types.String                                `tfsdk:"id"`
	PolicySetId types.String                                `tfsdk:"policy_set_id"`
	Items       []NetworkAccessAuthenticationRulesBulkItems `tfsdk:"items"`
}

type NetworkAccessAuthenticationRulesBulkItems struct {
	Id                       types.String                                        `tfsdk:"id"`
	Name                     types.String                                        `tfsdk:"name"`
	Default                  types.Bool                                          `tfsdk:"default"`
	Rank                     types.Int64                                         `tfsdk:"rank"`
	State                    types.String                                        `tfsdk:"state"`
	ConditionType            types.String                                        `tfsdk:"condition_type"`
	ConditionId              types.String                                        `tfsdk:"condition_id"`
	ConditionIsNegate        types.Bool                                          `tfsdk:"condition_is_negate"`
	ConditionAttributeName   types.String                                        `tfsdk:"condition_attribute_name"`
	ConditionAttributeValue  types.String                                        `tfsdk:"condition_attribute_value"`
	ConditionDictionaryName  types.String                                        `tfsdk:"condition_dictionary_name"`
	ConditionDictionaryValue types.String                                        `tfsdk:"condition_dictionary_value"`
	ConditionOperator        types.String                                        `tfsdk:"condition_operator"`
	Children                 []NetworkAccessAuthenticationRulesBulkItemsChildren `tfsdk:"children"`
	IdentitySourceName       types.String                                        `tfsdk:"identity_source_name"`
	IfAuthFail               types.String                                        `tfsdk:"if_auth_fail"`
	IfProcessFail            types.String                                        `tfsdk:"if_process_fail"`
	IfUserNotFound           types.String                                        `tfsdk:"if_user_not_found"`
}

type NetworkAccessAuthenticationRulesBulkItemsChildren struct {
	ConditionType   types.String                                                `tfsdk:"condition_type"`
	Id              types.String                                                `tfsdk:"id"`
	IsNegate        types.Bool                                                  `tfsdk:"is_negate"`
	AttributeName   types.String                                                `tfsdk:"attribute_name"`
	AttributeValue  types.String                                                `tfsdk:"attribute_value"`
	DictionaryName  types.String                                                `tfsdk:"dictionary_name"`
	DictionaryValue types.String                                                `tfsdk:"dictionary_value"`
	Operator        types.String                                                `tfsdk:"operator"`
	Children        []NetworkAccessAuthenticationRulesBulkItemsChildrenChildren `tfsdk:"children"`
}

type NetworkAccessAuthenticationRulesBulkItemsChildrenChildren struct {
	ConditionType   types.String `tfsdk:"condition_type"`
	Id              types.String `tfsdk:"id"`
	IsNegate        types.Bool   `tfsdk:"is_negate"`
	AttributeName   types.String `tfsdk:"attribute_name"`
	AttributeValue  types.String `tfsdk:"attribute_value"`
	DictionaryName  types.String `tfsdk:"dictionary_name"`
	DictionaryValue types.String `tfsdk:"dictionary_value"`
	Operator        types.String `tfsdk:"operator"`
}

//template:end types

//template:begin getPath
func (data NetworkAccessAuthenticationRulesBulk) getPath() string {
	return fmt.Sprintf("/api/v1/policy/network-access/policy-set/%v/authentication", url.QueryEscape(data.PolicySetId.ValueString()))
}

//template:end getPath

//template:begin getPathDelete

//template:end getPathDelete

//template:begin toBody
func (data NetworkAccessAuthenticationRulesBulk) toBody(ctx context.Context, state NetworkAccessAuthenticationRulesBulk) string {
	body := "[]"
	if len(data.Items) > 0 {
		body, _ = sjson.Set(body, "", []interface{}{})
		for _, item := range data.Items {
			itemBody := ""
			if !item.Id.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rule.id", item.Id.ValueString())
			}
			if !item.Name.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rule.name", item.Name.ValueString())
			}
			if !item.Default.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rule.default", item.Default.ValueBool())
			}
			if !item.Rank.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rule.rank", item.Rank.ValueInt64())
			}
			if !item.State.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rule.state", item.State.ValueString())
			}
			if !item.ConditionType.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rule.condition.conditionType", item.ConditionType.ValueString())
			}
			if !item.ConditionId.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rule.condition.id", item.ConditionId.ValueString())
			}
			if !item.ConditionIsNegate.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rule.condition.isNegate", item.ConditionIsNegate.ValueBool())
			}
			if !item.ConditionAttributeName.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rule.condition.attributeName", item.ConditionAttributeName.ValueString())
			}
			if !item.ConditionAttributeValue.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rule.condition.attributeValue", item.ConditionAttributeValue.ValueString())
			}
			if !item.ConditionDictionaryName.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rule.condition.dictionaryName", item.ConditionDictionaryName.ValueString())
			}
			if !item.ConditionDictionaryValue.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rule.condition.dictionaryValue", item.ConditionDictionaryValue.ValueString())
			}
			if !item.ConditionOperator.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rule.condition.operator", item.ConditionOperator.ValueString())
			}
			if len(item.Children) > 0 {
				itemBody, _ = sjson.Set(itemBody, "rule.condition.children", []interface{}{})
				for _, childItem := range item.Children {
					itemChildBody := ""
					if !childItem.ConditionType.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "conditionType", childItem.ConditionType.ValueString())
					}
					if !childItem.Id.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "id", childItem.Id.ValueString())
					}
					if !childItem.IsNegate.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "isNegate", childItem.IsNegate.ValueBool())
					}
					if !childItem.AttributeName.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "attributeName", childItem.AttributeName.ValueString())
					}
					if !childItem.AttributeValue.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "attributeValue", childItem.AttributeValue.ValueString())
					}
					if !childItem.DictionaryName.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "dictionaryName", childItem.DictionaryName.ValueString())
					}
					if !childItem.DictionaryValue.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "dictionaryValue", childItem.DictionaryValue.ValueString())
					}
					if !childItem.Operator.IsNull() {
						itemChildBody, _ = sjson.Set(itemChildBody, "operator", childItem.Operator.ValueString())
					}
					if len(childItem.Children) > 0 {
						itemChildBody, _ = sjson.Set(itemChildBody, "children", []interface{}{})
						for _, childChildItem := range childItem.Children {
							itemChildChildBody := ""
							if !childChildItem.ConditionType.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "conditionType", childChildItem.ConditionType.ValueString())
							}
							if !childChildItem.Id.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "id", childChildItem.Id.ValueString())
							}
							if !childChildItem.IsNegate.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "isNegate", childChildItem.IsNegate.ValueBool())
							}
							if !childChildItem.AttributeName.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "attributeName", childChildItem.AttributeName.ValueString())
							}
							if !childChildItem.AttributeValue.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "attributeValue", childChildItem.AttributeValue.ValueString())
							}
							if !childChildItem.DictionaryName.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "dictionaryName", childChildItem.DictionaryName.ValueString())
							}
							if !childChildItem.DictionaryValue.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "dictionaryValue", childChildItem.DictionaryValue.ValueString())
							}
							if !childChildItem.Operator.IsNull() {
								itemChildChildBody, _ = sjson.Set(itemChildChildBody, "operator", childChildItem.Operator.ValueString())
							}
							itemChildBody, _ = sjson.SetRaw(itemChildBody, "children.-1", itemChildChildBody)
						}
					}
					itemBody, _ = sjson.SetRaw(itemBody, "rule.condition.children.-1", itemChildBody)
				}
			}
			if !item.IdentitySourceName.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "identitySourceName", item.IdentitySourceName.ValueString())
			}
			if !item.IfAuthFail.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "ifAuthFail", item.IfAuthFail.ValueString())
			}
			if !item.IfProcessFail.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "ifProcessFail", item.IfProcessFail.ValueString())
			}
			if !item.IfUserNotFound.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "ifUserNotFound", item.IfUserNotFound.ValueString())
			}
			body, _ = sjson.SetRaw(body, "-1", itemBody)
		}
	}
	return body
}

//template:end toBody

//template:begin fromBody
func (data *NetworkAccessAuthenticationRulesBulk) fromBody(ctx context.Context, res gjson.Result) {
	if value := res; value.Exists() {
		data.Items = make([]NetworkAccessAuthenticationRulesBulkItems, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := NetworkAccessAuthenticationRulesBulkItems{}
			if cValue := v.Get("rule.id"); cValue.Exists() && cValue.Type != gjson.Null {
				item.Id = types.StringValue(cValue.String())
			} else {
				item.Id = types.StringNull()
			}
			if cValue := v.Get("rule.name"); cValue.Exists() && cValue.Type != gjson.Null {
				item.Name = types.StringValue(cValue.String())
			} else {
				item.Name = types.StringNull()
			}
			if cValue := v.Get("rule.default"); cValue.Exists() && cValue.Type != gjson.Null {
				item.Default = types.BoolValue(cValue.Bool())
			} else {
				item.Default = types.BoolNull()
			}
			if cValue := v.Get("rule.rank"); cValue.Exists() && cValue.Type != gjson.Null {
				item.Rank = types.Int64Value(cValue.Int())
			} else {
				item.Rank = types.Int64Null()
			}
			if cValue := v.Get("rule.state"); cValue.Exists() && cValue.Type != gjson.Null {
				item.State = types.StringValue(cValue.String())
			} else {
				item.State = types.StringNull()
			}
			if cValue := v.Get("rule.condition.conditionType"); cValue.Exists() && cValue.Type != gjson.Null {
				item.ConditionType = types.StringValue(cValue.String())
			} else {
				item.ConditionType = types.StringNull()
			}
			if cValue := v.Get("rule.condition.id"); cValue.Exists() && cValue.Type != gjson.Null {
				item.ConditionId = types.StringValue(cValue.String())
			} else {
				item.ConditionId = types.StringNull()
			}
			if cValue := v.Get("rule.condition.isNegate"); cValue.Exists() && cValue.Type != gjson.Null {
				item.ConditionIsNegate = types.BoolValue(cValue.Bool())
			} else {
				item.ConditionIsNegate = types.BoolNull()
			}
			if cValue := v.Get("rule.condition.attributeName"); cValue.Exists() && cValue.Type != gjson.Null {
				item.ConditionAttributeName = types.StringValue(cValue.String())
			} else {
				item.ConditionAttributeName = types.StringNull()
			}
			if cValue := v.Get("rule.condition.attributeValue"); cValue.Exists() && cValue.Type != gjson.Null {
				item.ConditionAttributeValue = types.StringValue(cValue.String())
			} else {
				item.ConditionAttributeValue = types.StringNull()
			}
			if cValue := v.Get("rule.condition.dictionaryName"); cValue.Exists() && cValue.Type != gjson.Null {
				item.ConditionDictionaryName = types.StringValue(cValue.String())
			} else {
				item.ConditionDictionaryName = types.StringNull()
			}
			if cValue := v.Get("rule.condition.dictionaryValue"); cValue.Exists() && cValue.Type != gjson.Null {
				item.ConditionDictionaryValue = types.StringValue(cValue.String())
			} else {
				item.ConditionDictionaryValue = types.StringNull()
			}
			if cValue := v.Get("rule.condition.operator"); cValue.Exists() && cValue.Type != gjson.Null {
				item.ConditionOperator = types.StringValue(cValue.String())
			} else {
				item.ConditionOperator = types.StringNull()
			}
			if cValue := v.Get("rule.condition.children"); cValue.Exists() {
				item.Children = make([]NetworkAccessAuthenticationRulesBulkItemsChildren, 0)
				cValue.ForEach(func(ck, cv gjson.Result) bool {
					cItem := NetworkAccessAuthenticationRulesBulkItemsChildren{}
					if ccValue := cv.Get("conditionType"); ccValue.Exists() && ccValue.Type != gjson.Null {
						cItem.ConditionType = types.StringValue(ccValue.String())
					} else {
						cItem.ConditionType = types.StringNull()
					}
					if ccValue := cv.Get("id"); ccValue.Exists() && ccValue.Type != gjson.Null {
						cItem.Id = types.StringValue(ccValue.String())
					} else {
						cItem.Id = types.StringNull()
					}
					if ccValue := cv.Get("isNegate"); ccValue.Exists() && ccValue.Type != gjson.Null {
						cItem.IsNegate = types.BoolValue(ccValue.Bool())
					} else {
						cItem.IsNegate = types.BoolNull()
					}
					if ccValue := cv.Get("attributeName"); ccValue.Exists() && ccValue.Type != gjson.Null {
						cItem.AttributeName = types.StringValue(ccValue.String())
					} else {
						cItem.AttributeName = types.StringNull()
					}
					if ccValue := cv.Get("attributeValue"); ccValue.Exists() && ccValue.Type != gjson.Null {
						cItem.AttributeValue = types.StringValue(ccValue.String())
					} else {
						cItem.AttributeValue = types.StringNull()
					}
					if ccValue := cv.Get("dictionaryName"); ccValue.Exists() && ccValue.Type != gjson.Null {
						cItem.DictionaryName = types.StringValue(ccValue.String())
					} else {
						cItem.DictionaryName = types.StringNull()
					}
					if ccValue := cv.Get("dictionaryValue"); ccValue.Exists() && ccValue.Type != gjson.Null {
						cItem.DictionaryValue = types.StringValue(ccValue.String())
					} else {
						cItem.DictionaryValue = types.StringNull()
					}
					if ccValue := cv.Get("operator"); ccValue.Exists() && ccValue.Type != gjson.Null {
						cItem.Operator = types.StringValue(ccValue.String())
					} else {
						cItem.Operator = types.StringNull()
					}
					if ccValue := cv.Get("children"); ccValue.Exists() {
						cItem.Children = make([]NetworkAccessAuthenticationRulesBulkItemsChildrenChildren, 0)
						ccValue.ForEach(func(cck, ccv gjson.Result) bool {
							ccItem := NetworkAccessAuthenticationRulesBulkItemsChildrenChildren{}
							if cccValue := ccv.Get("conditionType"); cccValue.Exists() && cccValue.Type != gjson.Null {
								ccItem.ConditionType = types.StringValue(cccValue.String())
							} else {
								ccItem.ConditionType = types.StringNull()
							}
							if cccValue := ccv.Get("id"); cccValue.Exists() && cccValue.Type != gjson.Null {
								ccItem.Id = types.StringValue(cccValue.String())
							} else {
								ccItem.Id = types.StringNull()
							}
							if cccValue := ccv.Get("isNegate"); cccValue.Exists() && cccValue.Type != gjson.Null {
								ccItem.IsNegate = types.BoolValue(cccValue.Bool())
							} else {
								ccItem.IsNegate = types.BoolNull()
							}
							if cccValue := ccv.Get("attributeName"); cccValue.Exists() && cccValue.Type != gjson.Null {
								ccItem.AttributeName = types.StringValue(cccValue.String())
							} else {
								ccItem.AttributeName = types.StringNull()
							}
							if cccValue := ccv.Get("attributeValue"); cccValue.Exists() && cccValue.Type != gjson.Null {
								ccItem.AttributeValue = types.StringValue(cccValue.String())
							} else {
								ccItem.AttributeValue = types.StringNull()
							}
							if cccValue := ccv.Get("dictionaryName"); cccValue.Exists() && cccValue.Type != gjson.Null {
								ccItem.DictionaryName = types.StringValue(cccValue.String())
							} else {
								ccItem.DictionaryName = types.StringNull()
							}
							if cccValue := ccv.Get("dictionaryValue"); cccValue.Exists() && cccValue.Type != gjson.Null {
								ccItem.DictionaryValue = types.StringValue(cccValue.String())
							} else {
								ccItem.DictionaryValue = types.StringNull()
							}
							if cccValue := ccv.Get("operator"); cccValue.Exists() && cccValue.Type != gjson.Null {
								ccItem.Operator = types.StringValue(cccValue.String())
							} else {
								ccItem.Operator = types.StringNull()
							}
							cItem.Children = append(cItem.Children, ccItem)
							return true
						})
					}
					item.Children = append(item.Children, cItem)
					return true
				})
			}
			if cValue := v.Get("identitySourceName"); cValue.Exists() && cValue.Type != gjson.Null {
				item.IdentitySourceName = types.StringValue(cValue.String())
			} else {
				item.IdentitySourceName = types.StringNull()
			}
			if cValue := v.Get("ifAuthFail"); cValue.Exists() && cValue.Type != gjson.Null {
				item.IfAuthFail = types.StringValue(cValue.String())
			} else {
				item.IfAuthFail = types.StringNull()
			}
			if cValue := v.Get("ifProcessFail"); cValue.Exists() && cValue.Type != gjson.Null {
				item.IfProcessFail = types.StringValue(cValue.String())
			} else {
				item.IfProcessFail = types.StringNull()
			}
			if cValue := v.Get("ifUserNotFound"); cValue.Exists() && cValue.Type != gjson.Null {
				item.IfUserNotFound = types.StringValue(cValue.String())
			} else {
				item.IfUserNotFound = types.StringNull()
			}
			data.Items = append(data.Items, item)
			return true
		})
	}
}

//template:end fromBody

//template:begin updateFromBody
func (data *NetworkAccessAuthenticationRulesBulk) updateFromBody(ctx context.Context, res gjson.Result) {
	for i := range data.Items {
		keys := [...]string{"rule.id", "rule.name", "rule.default", "rule.rank", "rule.state", "rule.condition.conditionType", "rule.condition.id", "rule.condition.isNegate", "rule.condition.attributeName", "rule.condition.attributeValue", "rule.condition.dictionaryName", "rule.condition.dictionaryValue", "rule.condition.operator", "identitySourceName", "ifAuthFail", "ifProcessFail", "ifUserNotFound"}
		keyValues := [...]string{data.Items[i].Id.ValueString(), data.Items[i].Name.ValueString(), strconv.FormatBool(data.Items[i].Default.ValueBool()), strconv.FormatInt(data.Items[i].Rank.ValueInt64(), 10), data.Items[i].State.ValueString(), data.Items[i].ConditionType.ValueString(), data.Items[i].ConditionId.ValueString(), strconv.FormatBool(data.Items[i].ConditionIsNegate.ValueBool()), data.Items[i].ConditionAttributeName.ValueString(), data.Items[i].ConditionAttributeValue.ValueString(), data.Items[i].ConditionDictionaryName.ValueString(), data.Items[i].ConditionDictionaryValue.ValueString(), data.Items[i].ConditionOperator.ValueString(), data.Items[i].IdentitySourceName.ValueString(), data.Items[i].IfAuthFail.ValueString(), data.Items[i].IfProcessFail.ValueString(), data.Items[i].IfUserNotFound.ValueString()}

		var r gjson.Result
		res.ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("rule.id"); value.Exists() && !data.Items[i].Id.IsNull() {
			data.Items[i].Id = types.StringValue(value.String())
		} else {
			data.Items[i].Id = types.StringNull()
		}
		if value := r.Get("rule.name"); value.Exists() && !data.Items[i].Name.IsNull() {
			data.Items[i].Name = types.StringValue(value.String())
		} else {
			data.Items[i].Name = types.StringNull()
		}
		if value := r.Get("rule.default"); value.Exists() && !data.Items[i].Default.IsNull() {
			data.Items[i].Default = types.BoolValue(value.Bool())
		} else {
			data.Items[i].Default = types.BoolNull()
		}
		if value := r.Get("rule.rank"); value.Exists() && !data.Items[i].Rank.IsNull() {
			data.Items[i].Rank = types.Int64Value(value.Int())
		} else {
			data.Items[i].Rank = types.Int64Null()
		}
		if value := r.Get("rule.state"); value.Exists() && !data.Items[i].State.IsNull() {
			data.Items[i].State = types.StringValue(value.String())
		} else {
			data.Items[i].State = types.StringNull()
		}
		if value := r.Get("rule.condition.conditionType"); value.Exists() && !data.Items[i].ConditionType.IsNull() {
			data.Items[i].ConditionType = types.StringValue(value.String())
		} else {
			data.Items[i].ConditionType = types.StringNull()
		}
		if value := r.Get("rule.condition.id"); value.Exists() && !data.Items[i].ConditionId.IsNull() {
			data.Items[i].ConditionId = types.StringValue(value.String())
		} else {
			data.Items[i].ConditionId = types.StringNull()
		}
		if value := r.Get("rule.condition.isNegate"); value.Exists() && !data.Items[i].ConditionIsNegate.IsNull() {
			data.Items[i].ConditionIsNegate = types.BoolValue(value.Bool())
		} else {
			data.Items[i].ConditionIsNegate = types.BoolNull()
		}
		if value := r.Get("rule.condition.attributeName"); value.Exists() && !data.Items[i].ConditionAttributeName.IsNull() {
			data.Items[i].ConditionAttributeName = types.StringValue(value.String())
		} else {
			data.Items[i].ConditionAttributeName = types.StringNull()
		}
		if value := r.Get("rule.condition.attributeValue"); value.Exists() && !data.Items[i].ConditionAttributeValue.IsNull() {
			data.Items[i].ConditionAttributeValue = types.StringValue(value.String())
		} else {
			data.Items[i].ConditionAttributeValue = types.StringNull()
		}
		if value := r.Get("rule.condition.dictionaryName"); value.Exists() && !data.Items[i].ConditionDictionaryName.IsNull() {
			data.Items[i].ConditionDictionaryName = types.StringValue(value.String())
		} else {
			data.Items[i].ConditionDictionaryName = types.StringNull()
		}
		if value := r.Get("rule.condition.dictionaryValue"); value.Exists() && !data.Items[i].ConditionDictionaryValue.IsNull() {
			data.Items[i].ConditionDictionaryValue = types.StringValue(value.String())
		} else {
			data.Items[i].ConditionDictionaryValue = types.StringNull()
		}
		if value := r.Get("rule.condition.operator"); value.Exists() && !data.Items[i].ConditionOperator.IsNull() {
			data.Items[i].ConditionOperator = types.StringValue(value.String())
		} else {
			data.Items[i].ConditionOperator = types.StringNull()
		}
		for ci := range data.Items[i].Children {
			keys := [...]string{"conditionType", "id", "isNegate", "attributeName", "attributeValue", "dictionaryName", "dictionaryValue", "operator"}
			keyValues := [...]string{data.Items[i].Children[ci].ConditionType.ValueString(), data.Items[i].Children[ci].Id.ValueString(), strconv.FormatBool(data.Items[i].Children[ci].IsNegate.ValueBool()), data.Items[i].Children[ci].AttributeName.ValueString(), data.Items[i].Children[ci].AttributeValue.ValueString(), data.Items[i].Children[ci].DictionaryName.ValueString(), data.Items[i].Children[ci].DictionaryValue.ValueString(), data.Items[i].Children[ci].Operator.ValueString()}

			var cr gjson.Result
			r.Get("rule.condition.children").ForEach(
				func(_, v gjson.Result) bool {
					found := false
					for ik := range keys {
						if v.Get(keys[ik]).String() == keyValues[ik] {
							found = true
							continue
						}
						found = false
						break
					}
					if found {
						cr = v
						return false
					}
					return true
				},
			)
			if value := cr.Get("conditionType"); value.Exists() && !data.Items[i].Children[ci].ConditionType.IsNull() {
				data.Items[i].Children[ci].ConditionType = types.StringValue(value.String())
			} else {
				data.Items[i].Children[ci].ConditionType = types.StringNull()
			}
			if value := cr.Get("id"); value.Exists() && !data.Items[i].Children[ci].Id.IsNull() {
				data.Items[i].Children[ci].Id = types.StringValue(value.String())
			} else {
				data.Items[i].Children[ci].Id = types.StringNull()
			}
			if value := cr.Get("isNegate"); value.Exists() && !data.Items[i].Children[ci].IsNegate.IsNull() {
				data.Items[i].Children[ci].IsNegate = types.BoolValue(value.Bool())
			} else {
				data.Items[i].Children[ci].IsNegate = types.BoolNull()
			}
			if value := cr.Get("attributeName"); value.Exists() && !data.Items[i].Children[ci].AttributeName.IsNull() {
				data.Items[i].Children[ci].AttributeName = types.StringValue(value.String())
			} else {
				data.Items[i].Children[ci].AttributeName = types.StringNull()
			}
			if value := cr.Get("attributeValue"); value.Exists() && !data.Items[i].Children[ci].AttributeValue.IsNull() {
				data.Items[i].Children[ci].AttributeValue = types.StringValue(value.String())
			} else {
				data.Items[i].Children[ci].AttributeValue = types.StringNull()
			}
			if value := cr.Get("dictionaryName"); value.Exists() && !data.Items[i].Children[ci].DictionaryName.IsNull() {
				data.Items[i].Children[ci].DictionaryName = types.StringValue(value.String())
			} else {
				data.Items[i].Children[ci].DictionaryName = types.StringNull()
			}
			if value := cr.Get("dictionaryValue"); value.Exists() && !data.Items[i].Children[ci].DictionaryValue.IsNull() {
				data.Items[i].Children[ci].DictionaryValue = types.StringValue(value.String())
			} else {
				data.Items[i].Children[ci].DictionaryValue = types.StringNull()
			}
			if value := cr.Get("operator"); value.Exists() && !data.Items[i].Children[ci].Operator.IsNull() {
				data.Items[i].Children[ci].Operator = types.StringValue(value.String())
			} else {
				data.Items[i].Children[ci].Operator = types.StringNull()
			}
			for cci := range data.Items[i].Children[ci].Children {
				keys := [...]string{"conditionType", "id", "isNegate", "attributeName", "attributeValue", "dictionaryName", "dictionaryValue", "operator"}
				keyValues := [...]string{data.Items[i].Children[ci].Children[cci].ConditionType.ValueString(), data.Items[i].Children[ci].Children[cci].Id.ValueString(), strconv.FormatBool(data.Items[i].Children[ci].Children[cci].IsNegate.ValueBool()), data.Items[i].Children[ci].Children[cci].AttributeName.ValueString(), data.Items[i].Children[ci].Children[cci].AttributeValue.ValueString(), data.Items[i].Children[ci].Children[cci].DictionaryName.ValueString(), data.Items[i].Children[ci].Children[cci].DictionaryValue.ValueString(), data.Items[i].Children[ci].Children[cci].Operator.ValueString()}

				var ccr gjson.Result
				cr.Get("children").ForEach(
					func(_, v gjson.Result) bool {
						found := false
						for ik := range keys {
							if v.Get(keys[ik]).String() == keyValues[ik] {
								found = true
								continue
							}
							found = false
							break
						}
						if found {
							ccr = v
							return false
						}
						return true
					},
				)
				if value := ccr.Get("conditionType"); value.Exists() && !data.Items[i].Children[ci].Children[cci].ConditionType.IsNull() {
					data.Items[i].Children[ci].Children[cci].ConditionType = types.StringValue(value.String())
				} else {
					data.Items[i].Children[ci].Children[cci].ConditionType = types.StringNull()
				}
				if value := ccr.Get("id"); value.Exists() && !data.Items[i].Children[ci].Children[cci].Id.IsNull() {
					data.Items[i].Children[ci].Children[cci].Id = types.StringValue(value.String())
				} else {
					data.Items[i].Children[ci].Children[cci].Id = types.StringNull()
				}
				if value := ccr.Get("isNegate"); value.Exists() && !data.Items[i].Children[ci].Children[cci].IsNegate.IsNull() {
					data.Items[i].Children[ci].Children[cci].IsNegate = types.BoolValue(value.Bool())
				} else {
					data.Items[i].Children[ci].Children[cci].IsNegate = types.BoolNull()
				}
				if value := ccr.Get("attributeName"); value.Exists() && !data.Items[i].Children[ci].Children[cci].AttributeName.IsNull() {
					data.Items[i].Children[ci].Children[cci].AttributeName = types.StringValue(value.String())
				} else {
					data.Items[i].Children[ci].Children[cci].AttributeName = types.StringNull()
				}
				if value := ccr.Get("attributeValue"); value.Exists() && !data.Items[i].Children[ci].Children[cci].AttributeValue.IsNull() {
					data.Items[i].Children[ci].Children[cci].AttributeValue = types.StringValue(value.String())
				} else {
					data.Items[i].Children[ci].Children[cci].AttributeValue = types.StringNull()
				}
				if value := ccr.Get("dictionaryName"); value.Exists() && !data.Items[i].Children[ci].Children[cci].DictionaryName.IsNull() {
					data.Items[i].Children[ci].Children[cci].DictionaryName = types.StringValue(value.String())
				} else {
					data.Items[i].Children[ci].Children[cci].DictionaryName = types.StringNull()
				}
				if value := ccr.Get("dictionaryValue"); value.Exists() && !data.Items[i].Children[ci].Children[cci].DictionaryValue.IsNull() {
					data.Items[i].Children[ci].Children[cci].DictionaryValue = types.StringValue(value.String())
				} else {
					data.Items[i].Children[ci].Children[cci].DictionaryValue = types.StringNull()
				}
				if value := ccr.Get("operator"); value.Exists() && !data.Items[i].Children[ci].Children[cci].Operator.IsNull() {
					data.Items[i].Children[ci].Children[cci].Operator = types.StringValue(value.String())
				} else {
					data.Items[i].Children[ci].Children[cci].Operator = types.StringNull()
				}
			}
		}
		if value := r.Get("identitySourceName"); value.Exists() && !data.Items[i].IdentitySourceName.IsNull() {
			data.Items[i].IdentitySourceName = types.StringValue(value.String())
		} else {
			data.Items[i].IdentitySourceName = types.StringNull()
		}
		if value := r.Get("ifAuthFail"); value.Exists() && !data.Items[i].IfAuthFail.IsNull() {
			data.Items[i].IfAuthFail = types.StringValue(value.String())
		} else {
			data.Items[i].IfAuthFail = types.StringNull()
		}
		if value := r.Get("ifProcessFail"); value.Exists() && !data.Items[i].IfProcessFail.IsNull() {
			data.Items[i].IfProcessFail = types.StringValue(value.String())
		} else {
			data.Items[i].IfProcessFail = types.StringNull()
		}
		if value := r.Get("ifUserNotFound"); value.Exists() && !data.Items[i].IfUserNotFound.IsNull() {
			data.Items[i].IfUserNotFound = types.StringValue(value.String())
		} else {
			data.Items[i].IfUserNotFound = types.StringNull()
		}
	}
}

//template:end updateFromBody

//template:begin isNull
func (data *NetworkAccessAuthenticationRulesBulk) isNull(ctx context.Context, res gjson.Result) bool {
	if len(data.Items) > 0 {
		return false
	}
	return true
}

//template:end isNull

//template:begin fromBodyUnknowns
func (data *NetworkAccessAuthenticationRulesBulk) fromBodyUnknowns(ctx context.Context, res gjson.Result) {
	// fromBodyUnknowns updates the Unknown Computed tfstate values from a JSON.
	// Known values are not changed (usual for Computed attributes with UseStateForUnknown or with Default).
	tflog.Debug(ctx, fmt.Sprintf("FROMBODYUNKNOWN: %s", res))
	tflog.Debug(ctx, fmt.Sprintf("DATADATADATA: %s", data))
	for i := range data.Items {
		tflog.Debug(ctx, fmt.Sprintf("FROMBODYUNKNOWNI: %s", i))
		tflog.Debug(ctx, fmt.Sprintf("FROMBODYUNKNOWNV: %s", data.Items[i]))

		keys := [...]string{"rule.name", "rule.default", "rule.rank", "rule.state", "rule.condition.conditionType", "rule.condition.id", "rule.condition.isNegate", "rule.condition.attributeName", "rule.condition.attributeValue", "rule.condition.dictionaryName", "rule.condition.dictionaryValue", "rule.condition.operator", "identitySourceName", "ifAuthFail", "ifProcessFail", "ifUserNotFound"}
		keyValues := [...]string{data.Items[i].Name.ValueString(), strconv.FormatBool(data.Items[i].Default.ValueBool()), strconv.FormatInt(data.Items[i].Rank.ValueInt64(), 10), data.Items[i].State.ValueString(), data.Items[i].ConditionType.ValueString(), data.Items[i].ConditionId.ValueString(), strconv.FormatBool(data.Items[i].ConditionIsNegate.ValueBool()), data.Items[i].ConditionAttributeName.ValueString(), data.Items[i].ConditionAttributeValue.ValueString(), data.Items[i].ConditionDictionaryName.ValueString(), data.Items[i].ConditionDictionaryValue.ValueString(), data.Items[i].ConditionOperator.ValueString(), data.Items[i].IdentitySourceName.ValueString(), data.Items[i].IfAuthFail.ValueString(), data.Items[i].IfProcessFail.ValueString(), data.Items[i].IfUserNotFound.ValueString()}

		var r gjson.Result
		res.Get("items").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if data.Items[i].Id.IsUnknown() {
			if value := res.Get("rule.id"); value.Exists() {
				data.Id = types.StringValue(value.String())
			} else {
				data.Id = types.StringNull()
			}
		}
		if value := r.Get("rule.id"); value.Exists() && !data.Items[i].Id.IsNull() {
			data.Items[i].Id = types.StringValue(value.String())
		} else {
			data.Items[i].Id = types.StringNull()
		}
	}
}

//template:end fromBodyUnknowns
